### ISSUE TITLE
Library dir

### ISSUE THREAD

**Issue by jubalh** [mhogomchungu/lxqt_wallet#1]
It seems liblxqtwallet.so wants to get installed in /usr/64 which is not in accordance with FHS. Could you change this?

**Comment by mhogomchungu** [comment]
Delete the build folder to start afresh and try again.

I usually get that when i run cmake after i have successfully build the project.

I get that behavior in all my projects so,there is something wrong i am doing consistently in all my project and the solution i know is to always start with a clean build folder if i want to run cmake again after i have already build the project or if i have changed a config option after i have run cmake.

**Comment by mhogomchungu** [comment]
Below is what i am getting here when i build with a clean build folder

```
[mtz@ink lxqt-wallet]$ cmake -DQT5=true -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_INSTALL_PREFIX=/usr ../projects/lxqt_wallet/
-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29") 
-- found gcrypt header file: /usr/include/gcrypt.h
-- found gcrypt library: /usr/lib64/libgcrypt.so
-- Checking for module 'libsecret-1'
--   Found libsecret-1, version 0.18.4
-- 
--------------------------------------------------------------------------
-- kwallet support NOT found,will not build kwallet functionality
-- -----------------------------------------------------------------------
-- 
--------------------------------------------------------------------------
-- libsecret support found,will build libsecret functionality
-- -----------------------------------------------------------------------
-- Configuring done
-- Generating done
-- Build files have been written to: /home/mtz/lxqt-wallet
[mtz@ink lxqt-wallet]$ make
Scanning dependencies of target lxqt_wallet-cli
[  4%] Building C object backend/CMakeFiles/lxqt_wallet-cli.dir/lxqt_wallet-cli.c.o
[  8%] Building C object backend/CMakeFiles/lxqt_wallet-cli.dir/lxqtwallet.c.o
[ 12%] Linking C executable lxqt_wallet-cli
[ 12%] Built target lxqt_wallet-cli
Scanning dependencies of target lxqtwallet-backend
[ 16%] Building C object backend/CMakeFiles/lxqtwallet-backend.dir/lxqtwallet.c.o
[ 20%] Linking C static library liblxqtwallet-backend.a
[ 20%] Built target lxqtwallet-backend
Scanning dependencies of target secretService
[ 24%] Building C object frontend/secret_service/CMakeFiles/secretService.dir/__/secret_service.c.o                                                                                                 
[ 28%] Linking C static library libsecretService.a
[ 28%] Built target secretService
[ 32%] Generating moc_task.cpp
[ 36%] Generating ui_changepassworddialog.h
[ 40%] Generating ui_password_dialog.h
[ 44%] Generating moc_changepassworddialog.cpp
[ 48%] Generating moc_lxqt_internal_wallet.cpp
[ 52%] Generating moc_password_dialog.cpp
[ 56%] Generating moc_lxqt_secret_service.cpp
Scanning dependencies of target lxqtwallet
[ 60%] Building CXX object frontend/CMakeFiles/lxqtwallet.dir/changepassworddialog.cpp.o
[ 64%] Building CXX object frontend/CMakeFiles/lxqtwallet.dir/password_dialog.cpp.o
[ 68%] Building CXX object frontend/CMakeFiles/lxqtwallet.dir/lxqt_internal_wallet.cpp.o
[ 72%] Building CXX object frontend/CMakeFiles/lxqtwallet.dir/lxqt_wallet.cpp.o
[ 76%] Building CXX object frontend/CMakeFiles/lxqtwallet.dir/lxqt_secret_service.cpp.o
[ 80%] Building CXX object frontend/CMakeFiles/lxqtwallet.dir/moc_changepassworddialog.cpp.o
[ 84%] Building CXX object frontend/CMakeFiles/lxqtwallet.dir/moc_lxqt_internal_wallet.cpp.o
[ 88%] Building CXX object frontend/CMakeFiles/lxqtwallet.dir/moc_password_dialog.cpp.o
[ 92%] Building CXX object frontend/CMakeFiles/lxqtwallet.dir/moc_lxqt_secret_service.cpp.o
[ 96%] Building CXX object frontend/CMakeFiles/lxqtwallet.dir/moc_task.cpp.o
[100%] Linking CXX shared library liblxqtwallet.so
[100%] Built target lxqtwallet
[mtz@ink lxqt-wallet]$ su
Password: 
[root@ink lxqt-wallet]# make install
[ 12%] Built target lxqt_wallet-cli
[ 20%] Built target lxqtwallet-backend
[ 28%] Built target secretService
[100%] Built target lxqtwallet
Install the project...
-- Install configuration: "RELEASE"
-- Up-to-date: /usr/include/lxqt/lxqtwallet.h
-- Installing: /usr/bin/lxqt_wallet-cli
-- Up-to-date: /usr/share/lxqt_wallet/translations.qm/german_DE.qm
-- Up-to-date: /usr/share/lxqt_wallet/translations.qm/greek_GR.qm
-- Up-to-date: /usr/share/lxqt_wallet/translations.qm/dutch_NL.qm
-- Up-to-date: /usr/share/lxqt_wallet/translations.qm/french_FR.qm
-- Up-to-date: /usr/share/lxqt_wallet/translations.qm/spanish_ES.qm
-- Installing: /usr/lib64/liblxqtwallet.so.2.0.0
-- Up-to-date: /usr/lib64/liblxqtwallet.so
-- Up-to-date: /usr/include/lxqt/lxqt_wallet.h
-- Installing: /usr/lib64/pkgconfig/lxqtwallet.pc
[root@ink lxqt-wallet]# 

```

**Comment by jubalh** [comment]
Thanks for the quick reply.
We will have to dig deeper to find the real problem. I will see when I have some free time

**Comment by mhogomchungu** [comment]
Can you confirm that starting with a clean build folder solves the problem.

**Comment by jubalh** [comment]
Yes, seems like it

**Comment by mhogomchungu** [comment]
Thanks.

I am closing this one since the project can be installed correctly but feel free to continue commenting if anything else comes  up.

**Comment by jubalh** [comment]
Well, I am using a build service to build the package and sometimes it doesnst start clean. So this should be fixed if it should go into a a distro at some point. (For example when you the project will be an official LXQt project)

**Comment by mhogomchungu** [comment]
I agree,i tried to fix it and failed as i could not see what was causing the problem.

There are a lot of things i do not know and understand about cmake build system and i what i have so far in all my projects is a result of throwing stuff at the wall and go with whatever sticks and move around what stuck from project to project with a net result of the same problems showing up in all my projects.

**Comment by mhogomchungu** [comment]
The CMakeLists will probably need to be redone and removing Qt4 and KDE4 support since lxqt now depends only on Qt5.

**Comment by jubalh** [comment]
Sure. I understand what you did. Anyways I wonder why you closed the issue until its totally solved :-)

**Comment by mhogomchungu** [comment]
I usually close bug reports when the primary issue is resolved and i though the primary issue was that you were not building the project from a clean build folder and i proposed a solution that worked.

I usually close bug reports this way while allowing discussion to continue because sometimes people just leave after their inquire is answered without closing the bug report.

I am reopening it since you seem to prefer it that way.

**Comment by mhogomchungu** [comment]
I just redid the build system and the problem should now be gone since install paths are now taken from "GNUInstallDirs" package.

**Comment by jubalh** [comment]
Good to hear :-)
Once there is a new release I will test it.

**Comment by mhogomchungu** [comment]
i am confused.

I though you were reviewing the library to decide if it is good enough to be included as a "blessed" component of lxqt?

I have made incompatible changes with previous versions to align the API with official naming and it will not make sense to make a new release without anybody from lxqt reviewing it and decide one way or the other.

**Comment by mhogomchungu** [comment]
I am closing this one since i think the reported problem is now fixed.

Feel free to comment further if anything comes up.

**Comment by jubalh** [comment]
I am mostly concerned with [packaging this library for openSUSE](https://build.opensuse.org/package/show/X11:LXQt/lxqt-wallet). Also I support having it as an official LXQt component.

**Comment by mhogomchungu** [comment]
The library is ready for release and i think it will be better if you could test instead of after its released to avoid carrying local patches to fix whatever issue you may find when testing the released version.

**Comment by jubalh** [comment]
You already have [seven releases](https://github.com/mhogomchungu/lxqt_wallet/releases).
If you say your library is ready its either time to create a new one, or create a beta release which will be tested and after some days/weeks will become a normal release.
However It should not be me who provides the tarball but you. Thus creating a release on GitHub and one can grab the release tarball and build it.

**Comment by mhogomchungu** [comment]
I gave you an advance notice just incase you will need to customize the release to adjust it to opensuse packaging policies if there are any.If they are there and the release violates them,i though it will be better if you could tell me in advance so that i can i can add them before the release to save you the trouble of carrying local patches for those customization.

If you or opensuse have no opinions on how the end result will be then wait until i make a new release for you to test and package.

**Comment by jubalh** [comment]
And I appreciate your heads up.
Like I mentioned earlier, I already packaged version 2.2.0 of you package in the openSUSE devel project X11:LXQt. It's not in the official distribution but users who want to test it can get it from there.

For me the process is like this: you create releases and beta releases, I build them.
I give you feedback about the current state.
At some point when LXQt upstream is looking into adopting lxqt_wallet officially some of the developers certainly will screen your code more thouroughly. And once its part of official LXQt I will push it from the openSUSE devel project to the official distribution. :-)

**Comment by mhogomchungu** [comment]
New version of lxqt-wallet is out: https://github.com/mhogomchungu/lxqt_wallet/releases/tag/3.0.0

**Comment by jubalh** [comment]
@mhogomchungu Aaaand already built :)
See https://build.opensuse.org/package/show/X11:LXQt/lxqt-wallet
