### ISSUE TITLE
latest 3.2.0 release fails to build

### ISSUE THREAD

**Issue by david-geiger** [mhogomchungu/lxqt_wallet#16]
Hi,

I tried on Mageia Linux (Cauldron) to build latest 3.2.0 release but it fails to build due to a format-security issue:

> [ 31%] Built target translations
/home/iurt/rpmbuild/BUILD/lxqt-wallet-3.2.0/backend/lxqt_wallet-cli.c: In function '_openWallet':
/home/iurt/rpmbuild/BUILD/lxqt-wallet-3.2.0/backend/lxqt_wallet-cli.c:197:5: error: format not a string literal and no format arguments [-Werror=format-security]
  197 |     printf(lxqt_wallet_gettext("enter wallet name: "));
      |     ^~~~~~
/home/iurt/rpmbuild/BUILD/lxqt-wallet-3.2.0/backend/lxqt_wallet-cli.c:207:13: error: format not a string literal and no format arguments [-Werror=format-security]
  207 |             printf(lxqt_wallet_gettext("enter wallet password: "));
      |             ^~~~~~
/home/iurt/rpmbuild/BUILD/lxqt-wallet-3.2.0/backend/lxqt_wallet-cli.c:210:13: error: format not a string literal and no format arguments [-Werror=format-security]
  210 |             printf(lxqt_wallet_gettext("re enter wallet password: "));
      |             ^~~~~~
/home/iurt/rpmbuild/BUILD/lxqt-wallet-3.2.0/backend/lxqt_wallet-cli.c:236:9: error: format not a string literal and no format arguments [-Werror=format-security]
  236 |         printf(lxqt_wallet_gettext("enter wallet password: "));
      |         ^~~~~~
cc1: some warnings being treated as errors
gmake[2]: *** [backend/CMakeFiles/lxqt_wallet-cli.dir/build.make:85: backend/CMakeFiles/lxqt_wallet-cli.dir/lxqt_wallet-cli.c.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....

Attached full build log:
[build.0.20200802065203.log](https://github.com/lxqt/lxqt_wallet/files/5011761/build.0.20200802065203.log)

Regards,
David

**Comment by mhogomchungu** [comment]
Can you try to build again using the git version.

**Comment by david-geiger** [comment]
Yes latest commit fixes build, thanks!

**Comment by mhogomchungu** [comment]
Thanks for the confirmation and i just made a new release with a fix: https://github.com/lxqt/lxqt_wallet/releases/tag/3.2.1
