### ISSUE TITLE
Is this project planned to be ported to Qt6?

### ISSUE THREAD

**Issue by david-geiger** [mhogomchungu/lxqt_wallet#53]
Hi,

lxqt now switched to Qt6, is also this project planned to switch/be ported to Qt6?

Regards,
david

**Comment by david-geiger** [comment]
zulucrypt uses a bundled copy of lxqt_wallet wich was ported to Qt6:

https://github.com/mhogomchungu/zuluCrypt/tree/master/external_libraries/lxqt_wallet

**Comment by mhogomchungu** [comment]
Yes, it will be ported to Qt6 within a week or two.

SiriKali is also ported to Qt6 and has an internal copy of lxqt_wallet.

Both of these projects uses a bundled version only when a system installed version is not detected at build time.

https://github.com/mhogomchungu/sirikali/tree/master/src/3rdParty/lxqt_wallet

**Comment by david-geiger** [comment]
Good news :)

**Comment by mhogomchungu** [comment]
The project is already ported to Qt6.

**Comment by david-geiger** [comment]
So a new release tarball would be great :)

**Comment by mhogomchungu** [comment]
New release is out: https://github.com/lxqt/lxqt_wallet/releases/tag/4.0.0
