### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by jubalh** [mhogomchungu/lxqt_wallet#6]
Please add simple instructions on how to use to the README.

**Comment by mhogomchungu** [comment]
Done, will appreciate any comment if you find anything lacking.

**Comment by jubalh** [comment]
Very nice thank you!
As I understand it this is not just a library with API, it also can be used as wallet application that can be started with an lxqt-session, right?
If so, could describe that use case too?

**Comment by mhogomchungu** [comment]
This is just a library with an API and it can not be used on its own.

**Comment by jubalh** [comment]
Thanks!
